//
// Created by NineDollar on 2022/4/17.
//

#ifndef DATASTRUCTURECOURSE_DELETESAMENODE_H
#define DATASTRUCTURECOURSE_DELETESAMENODE_H

void test2_10();

#endif //DATASTRUCTURECOURSE_DELETESAMENODE_H
