//
// Created by NineDollar on 2022/4/17.
//

#ifndef DATASTRUCTURECOURSE_SEPARATIONOFPOSITIVENEGATIVE_H
#define DATASTRUCTURECOURSE_SEPARATIONOFPOSITIVENEGATIVE_H

void test2_14();
#endif //DATASTRUCTURECOURSE_SEPARATIONOFPOSITIVENEGATIVE_H
