//
// Created by NineDollar on 2022/4/16.
//

#ifndef DATASTRUCTURECOURSE_2_6_3_INTERSECTION_H
#define DATASTRUCTURECOURSE_2_6_3_INTERSECTION_H

void test2_6_3();

#endif //DATASTRUCTURECOURSE_2_6_3_INTERSECTION_H
